### ISSUE TITLE
Ertekeles

### ISSUE THREAD

**Issue by Robert5555** [Teaching-projects/SZE-FordProg-2021-Elastic#1]

**Comment by hegyhati** [comment]
A szabalyrendszer nem tul combos, de a kornyezet szepen kore van rakva. (Ki most mobilnetrol vonatrol nem probalom, de elhiszem, hogy tesztelve volt.) Mivel a FordProgos vonal annyira nem eros, hajlanek a 4-es fele, de utolso vizsgam az SZE-n, ugyhogy megy az otos.

**Comment by gh0o5t** [comment]
Koszonom szepen :)
